service: kamal-ec2-app-launch
image: "${BACKEND_IMAGE}:${CI_COMMIT_SHA}"

builder:
  dockerfile: Dockerfile.production
  arch: amd64

registry:
  server: ${CI_REGISTRY}
  username: ${CI_REGISTRY_USER}
  password: ${CI_REGISTRY_PASSWORD}

servers:
  web:
    hosts:
      - "ubuntu@${DOMAIN_NAME}"
    labels:
      app: kamal-ec2-app-launch
    env:
      APP_PORT: 3000
      API_PORT: 8000
      DB_PORT: 5432
accessories:
  db:
    image: postgres:latest
    host: "ubuntu@${DOMAIN_NAME}"
    port: 5432
    env:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    health_check:
#      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s

env:
  secret:
    - DATABASE_URL
    - REDIS_URL
  clear:
    APP_PORT: 3000
    API_PORT: 8000
    DB_PORT: 5432
    NEXTAUTH_URL: http://localhost:3000
    AUTH_URL: http://localhost:3000